### ISSUE TITLE
Important message

### ISSUE THREAD

**Issue by ryancblack** [hyperwing/RetrieveSlackHistory#6]
https://github.com/hyperwing/RetrieveSlackHistory/blob/7ec93d9a21cd15e2fa17a6f137eca1bd0eb35bbc/venv/main.py#L15

You likely do not intend for this to be on GitHub. I didn't find an easy way to contact you other than this but I'm sure you'll see this issue. 

Cheers!

**Comment by hyperwing** [comment]
lol, it's fine. Its a defunct channel and it was mostly just as a workaround

**Comment by ryancblack** [comment]
Not to harp on this but I'd feel bad if I weren't explicit - tokens like this act _as your user._ This means irrespective of the intended use case this token may be used to act fully as you in the Slack Workspace entirely, e.g. all channels, reading chats, sending messages/files, downloading files, etc.

If you don't want to delete the repo (losing issues, creation date, etc.) you can still force overwrite it in a manner that removes the token and, equally importantly, the prior commits that would still contain it.

If you have questions on this I'm happy to help. This popped in my normal recon related to other efforts to be clear but it's just as easy for someone less scrupulous to cause you a lot of professional grief with the same.

Have a good week ahead.
